import type { Metadata } from "next";
import { SERVICE_AREAS, SITE } from "../../lib/site";

const title = "Contact Inna Benyukhis";
const description = "Contact Inna Benyukhis for virtual functional nutrition consultations in Buda, Kyle, Austin, San Marcos, and Central Texas.";

export const metadata: Metadata = { title, description, alternates: { canonical: "/contact" }, openGraph: { title, description, url: "/contact" } };

export default function ContactPage() {
  return <article className="bg-gradient-to-br from-[#f4fbf5] to-white py-24"><div className="mx-auto max-w-4xl px-6"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#238b45]">Contact Empowered Wellness with Inna</p><h1 className="mt-4 text-4xl font-bold text-[#183B10] md:text-6xl">Start with a complimentary conversation</h1><p className="mt-6 max-w-3xl text-xl leading-relaxed text-gray-700">Virtual consultations are available for clients in Buda, Kyle, Austin, San Marcos, and throughout Central Texas. Use the booking link or email to ask whether the service is a fit for your goals.</p><div className="mt-10 grid gap-6 md:grid-cols-2"><a href={SITE.bookingUrl} target="_blank" rel="noreferrer" className="rounded-3xl bg-[#238b45] p-8 text-white transition hover:bg-[#183B10]"><h2 className="text-2xl font-bold">Book a complimentary call</h2><p className="mt-3 text-white/85">Choose a time to discuss your goals and service options.</p></a><div className="rounded-3xl border border-gray-200 bg-white p-8"><h2 className="text-2xl font-bold text-[#183B10]">Email</h2><a href={`mailto:${SITE.email}`} className="mt-3 inline-block font-semibold text-[#238b45]">{SITE.email}</a><h2 className="mt-7 text-2xl font-bold text-[#183B10]">Phone</h2><a href={`tel:${SITE.phone}`} className="mt-3 inline-block font-semibold text-[#238b45]">(312) 404-4675</a></div></div><section className="mt-14 rounded-3xl bg-white p-8 shadow-sm"><h2 className="text-2xl font-bold text-[#183B10]">Central Texas service area</h2><p className="mt-3 text-gray-700">Core virtual service area:</p><ul className="mt-5 flex flex-wrap gap-3">{SERVICE_AREAS.map((area) => <li key={area.name} className="rounded-full bg-[#f4fbf5] px-4 py-2 font-semibold text-[#183B10]">{area.name}, {area.region}</li>)}</ul><p className="mt-6 text-sm leading-relaxed text-gray-600">Nutrition support is educational and does not provide diagnosis, emergency care, or medical treatment.</p></section></div></article>;
}
